version: '3'

services:
#   app:
#     image: golang:latest
#     container_name: photography-website
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./database:/app/database
#       - ./models:/app/models
#     ports:
#       - "8080:8080"  

  db:
    image: mysql:latest
    container_name: jwt_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
